### ISSUE TITLE
add open by default

### ISSUE THREAD

**Issue by wmartinmimi** [martinmimigames/little-file-explorer#11]

**Comment by wmartinmimi** [comment]
now have "open with" with option to choose default

**Comment by wmartinmimi** [comment]
Should now be available (v4.7).
Click here for [Github release](https://github.com/martinmimigames/little-file-explorer/releases/tag/v4.7)
F-droid may take a while to catch up.

**Comment by robsmith11** [comment]
> Now have "open with" with option to choose default. Should be available next release.

@wmartinmimi is the "open with" feature still present?

I just installed v4.14 from F-Droid, but only see "Open", "Details", and "Share" when I tap a file.
