### ISSUE TITLE
Hidden files litter certain folders

### ISSUE THREAD

**Issue by Snord9** [martinmimigames/little-file-explorer#25]
DOT-files, like .thumbnal___ files should remain hidden

SUGGEST
default: do NOT show
settings toggle so Show

**Comment by wmartinmimi** [comment]
True, I will add that later. It will probably exist in the sandwich button on the top right.

**Comment by wmartinmimi** [comment]
Added "toggle hidden" button that shows or hides hidden files (dot files), defaults to not show.
Feature should be available next release.

**Comment by wmartinmimi** [comment]
Now added in Little File Explorer v4.10

You can download it via:
- [Github](https://github.com/martinmimigames/little-file-explorer/releases/tag/v4.10)
- [Official website](https://martinmimigames.github.io/projects/little-file-explorer/index.html)
- [F-droid](https://f-droid.org/packages/com.martinmimigames.simplefileexplorer/) (may take a while to update)
