### ISSUE TITLE
TAP an image file .. and

### ISSUE THREAD

**Issue by Snord9** [martinmimigames/little-file-explorer#26]
Navigate to a folder with a few image files, and
TAP an imagefile:

MENU shows, to Open, Share or Cancel =Second-guesses obvious intent for tap
. . . SUGGEST .. Ditch the menu .. just DIRECTLY open the imagefile
. . . . "Share" is already offered in LongPress (Marked) context

magefile name is indeed handed off to sysdefault image handler =GOOD
BUT .. cannot SwipeL-or-R to sibling images .. stuck on that one file
THIS MAY BE the ImageViewer app's behaviour

**Comment by wmartinmimi** [comment]
## Removing the share button from menu
It is probably redundent, so I will likely remove it.

## Removing the menu
I plan to add a `details` button, so currently I plan to keep it.

## Image Viewer Swiping
Swiping is currently working on my phone on both Image viewer I have tested (1. The system default gallery, 2. A third-party general file viewer). It might be app specific behaviour.

**Comment by Spark4000** [comment]
Unrelated, but would like to ask if a recycle bin feature is something you might consider? Thanks for a nice application
