### ISSUE TITLE
TopLeft storage stats area shows Available 0.2TB .. Capacity 0.22TB

### ISSUE THREAD

**Issue by Snord9** [martinmimigames/little-file-explorer#28]
TopLeft storage stats area shows item NAME, then
Available size 0.2TB
Capacity size 0.22TB

Fone internal storage should show in gB, not tB
No external storage (ever) attached

MotoEdge2022
android 12

**Comment by wmartinmimi** [comment]
Now modified in Little File Explorer v4.9

You can download it via:
- [Github](https://github.com/martinmimigames/little-file-explorer/releases/tag/v4.9)
- [Official website](https://martinmimigames.github.io/projects/little-file-explorer/index.html)
- [F-droid](https://f-droid.org/packages/com.martinmimigames.simplefileexplorer/) (may take a while to update)
