### ISSUE TITLE
[Feature Request] Sorting

### ISSUE THREAD

**Issue by Cwpute** [martinmimigames/little-file-explorer#29]
**Describe your idea**
An option to sort files by ascending/descending name, size, or date created.
Remembering the sorting method for each folder would be great too but not mandatory.

**Describe why you want the idea incorprated**
When folders exceed 20 somethin files, it can become tedious to browse all of them to find the right one, especialy if their name look the same.
My personal exemple would be my audio recordings folders: they're automatically named after the date i record them on, but sometimes i rename them so i remember what they are about, which completely ruins the sorting if the files are sorted by alphabetical order. If i were to have Date creation sorting, that would help me browse these recordings more efficiently.

**Comment by wmartinmimi** [comment]
Added different sorting types. (A-z, z-A, by oldest, by earliest)
Should be available next release.

**Comment by wmartinmimi** [comment]
Now added in Little File Explorer v4.10

You can download it via:
- [Github](https://github.com/martinmimigames/little-file-explorer/releases/tag/v4.10)
- [Official website](https://martinmimigames.github.io/projects/little-file-explorer/index.html)
- [F-droid](https://f-droid.org/packages/com.martinmimigames.simplefileexplorer/) (may take a while to update)

**Comment by Cwpute** [comment]
> I suggest you to rename your files after the date and time stamps. Why would you remove those from name anyways ?

because the nume would be super long i wouldn't be able to quickly see the name i gave them ;)
