### ISSUE TITLE
Options overwritten

### ISSUE THREAD

**Issue by shuvashish76** [martinmimigames/little-file-explorer#3]
![Screenshot_20221218-215328](https://user-images.githubusercontent.com/48226312/208308784-2f336dde-7f9f-4ea9-8388-f909c760d392.png)

Steps to reproduce:

1. Long click any folder/file
2. Click on the options menu
(or reverse)

App version: 4.4 (6)

**Comment by wmartinmimi** [comment]
thank you for reporting! :>
Should now be fixed on on newest version (v4.5)

**Comment by wmartinmimi** [comment]
You can close it if you find it fixed.

**Comment by shuvashish76** [comment]
Thanks for the quick-fix.
