### ISSUE TITLE
`share` in file menu

### ISSUE THREAD

**Issue by asklow** [martinmimigames/little-file-explorer#31]
There's `share selected` under hamburger. But also provide it under file menu, when clicking on the file. Would be more easier than to hold it down.

**Comment by wmartinmimi** [comment]
I agree.
I have added the button back.
Should be available next release.

**Comment by wmartinmimi** [comment]
Now re-added in Little File Explorer v4.10

You can download it via:
- [Github](https://github.com/martinmimigames/little-file-explorer/releases/tag/v4.10)
- [Official website](https://martinmimigames.github.io/projects/little-file-explorer/index.html)
- [F-droid](https://f-droid.org/packages/com.martinmimigames.simplefileexplorer/) (may take a while to update)
