### ISSUE TITLE
[Feature Request] Always open LFE at root folder

### ISSUE THREAD

**Issue by Cwpute** [martinmimigames/little-file-explorer#39]
**Describe your idea**
Optiwn to make LFE always start on the root folder.

**Describe why you want the idea incorprated**
Currently, LFE opens the last browsed folder, but it can get a bit disorienting, understanding which folder you are in, where is the folder you want to get to relative to this one, then browsing back several folders before setting yourself on the right track. Allowing LFE to open at root folder would help minize a lot of thinking and browsing relative to these situations.

**Comment by wmartinmimi** [comment]
Behaviour now reverted in Little File Explorer v4.12

For most device it now opens at /storage/emulated/0

You can download it via:
- [Github](https://github.com/martinmimigames/little-file-explorer/releases/tag/v4.12)
- [Official website](https://martinmimigames.github.io/projects/little-file-explorer/)
- [F-droid](https://f-droid.org/packages/com.martinmimigames.simplefileexplorer/) (may take a while to update)

**Comment by leao-nardo** [comment]
it could have the 2 options . start at : root / last folder
