### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [martinmimigames/little-file-explorer#4]
```
> Task :app:processReleaseResources FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:processReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     /builds/fdroid/fdroiddata/build/com.martinmimigames.simplefileexplorer/app/build/intermediates/packaged_manifests/release/AndroidManifest.xml:16: error: resource drawable/folder (aka com.martinmimigames.simplefileexplorer:drawable/folder) not found.
     error: failed processing manifest.
```
ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/3512094633#L589

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/ec934a282c9b462ab43c4a003137825b1e9352dc

**Comment by wmartinmimi** [comment]
The drawable folder was gone. I have updated the tag (still same name), should now be fixed.
Btw, is there an f-droid build system I can download and use to test my code before I set a release?
Doing so might reduce the amount of errors we might face when I create a new release in the future.

**Comment by licaon-kter** [comment]
> Btw, is there an f-droid build system I can download and use to test my code before I set a release?

https://f-droid.org/docs/Build_Server_Setup/

https://f-droid.org/docs/Installing_the_Server_and_Repo_Tools/

etc in the Docs

**Comment by licaon-kter** [comment]
It needs 16? https://github.com/martinmimigames/little-file-explorer/blob/v4.5/app/build.gradle#L46

Trying now with 17: https://packages.debian.org/bullseye/openjdk-17-jdk-headless

**Comment by licaon-kter** [comment]
Builds fine: https://gitlab.com/fdroid/fdroiddata/-/commit/dc797a7502bdbcbadfa1772b8f46ee8a8f487525

**Comment by licaon-kter** [comment]
And again: https://web.archive.org/web/20230126070318/https://monitor.f-droid.org/builds/log/com.martinmimigames.simplefileexplorer/9

**Comment by wmartinmimi** [comment]
I think it didn't get the git submodule at ```app/src/main/java/mg/utils```

**Comment by wmartinmimi** [comment]
did it ran
```bash
git submodule init
git submodule update
```

**Comment by licaon-kter** [comment]
We need to specify in the recipe to do that...

Already fixed in https://gitlab.com/fdroid/fdroiddata/-/commit/d4526504afe3cf33cf9272b8890c13c939b62891 by @linsui ;)

**Comment by wmartinmimi** [comment]
i think you can run both command every time a git repo is used. They don't give errors if nothing is there, and doesn't take up much time. It would have the benefit of reducing checking and wasted compilation if random people added submodules.

Unless you already do that! :>
