### ISSUE TITLE
[Bug] Can't read files with a hashtag (#) in their name

### ISSUE THREAD

**Issue by Cwpute** [martinmimigames/little-file-explorer#42]
**Describe the bug**
Files with a hashtag (#) in their title can be opened, but the app that should open them fails to read them. Videos appear as 00:00 lenght videos, pdf can't be read, images fail to load... The hashtag can be either from the file creation or after its name has been changed. Deleting the hashtag from their name allow the files to be read as normal.
It isn't a file problem since i can open them from the built-in file browser, or from other apps.
Folders with a hashtag in their name can be read correctly though.

**To Reproduce**
1. Choose a file in your system
2. Add a # to their name
3. Try to open the files from Little File Explorer

**Expected Behaviour**
Files should open like any other.

**[Optional] Versioning  information**
- App Version: 4.11
- OS: Android 11

**[Optional] Additional information**
Maybe this problem extends to other special characters, it might be worth checking.
Originally posted an issue at https://github.com/moneytoo/Player/issues/512

**Comment by wmartinmimi** [comment]
Ngl, quite an interesting bug.

The bug is due to url encodings, and a bug fix should be easy.

Currently, identified issue causing characters are ```#``` and ```%```. A simple workaround before bug fix is to use other characters.

**Comment by wmartinmimi** [comment]
Should now fixed in Little File Explorer v4.13

You can download it via:
- [Github](https://github.com/martinmimigames/little-file-explorer/releases/tag/v4.13)
- [Official website](https://martinmimigames.github.io/projects/little-file-explorer/)
- [F-droid](https://f-droid.org/packages/com.martinmimigames.simplefileexplorer/) (may take a while to update)
