### ISSUE TITLE
[Bug] Last new folder name as pre-entered text

### ISSUE THREAD

**Issue by Cwpute** [martinmimigames/little-file-explorer#57]
**Describe the bug**
Ef you create several new folders in a row, the next new folder's text-area for entering its name will always be pre-filled with the last new folder's name.
I'm not sure wether this is a bug or a feature.

**To Reproduce**
1. Create a new folder with any name, for example `test`
2. Create another new folder
3. The text-area for entering its name will be filled with the previous, in this example `test`

**Expected Behaviour**
I don't see any situation in which you'd like to create several folders with almost the same name. In other file browsers, the expected behavior is to have this text-area always empty.

**Alternatives**
This behavior could be kept as is if it is useful to some, but have the pre-filled text selected, so that most users will only have to type new text in, whereas others who want to use the previous new folder's name will only be one click away from using it, by deselecting it.

**Comment by wmartinmimi** [comment]
Now clear everytime in Little File Explorer v4.14

You can download it via:
- [Github](https://github.com/martinmimigames/little-file-explorer/releases/tag/v4.14)
- [Official website](https://martinmimigames.github.io/projects/little-file-explorer/)
- [F-droid](https://f-droid.org/packages/com.martinmimigames.simplefileexplorer/) (may take a while to update)
