### ISSUE TITLE
Space between files and folders

### ISSUE THREAD

**Issue by Cwpute** [martinmimigames/little-file-explorer#59]
I realized lately the files and folders are separated in their own little list. Each section is then preceded by its name `Folders:` and `Files:`.

I don't know if there is anything else that needs it own separate list ?
Anyway, i was thinking that the little space taken by the titles of the lists could be kept, but the titles of the lists hidden. It would keep the differenciation between the two lists and give a cleaner look, without losing important information (as you can already tell folders are folders by their icon, and files are files… because they have other icons).

It's really a small thing but would be nice nonetheless.

**Comment by wmartinmimi** [comment]
Cleared in Little File Explorer v4.14

You can download it via:
- [Github](https://github.com/martinmimigames/little-file-explorer/releases/tag/v4.14)
- [Official website](https://martinmimigames.github.io/projects/little-file-explorer/)
- [F-droid](https://f-droid.org/packages/com.martinmimigames.simplefileexplorer/) (may take a while to update)
