### ISSUE TITLE
[Feature Request] Remove folder name

### ISSUE THREAD

**Issue by Cwpute** [martinmimigames/little-file-explorer#60]
**Describe your idea**
Remove the Name at the end of the file list, since the name can already be seen in the adress bar.

**[Optional] Describe any implementations you've considered**
Just remove the folder name at the end of the files list.
If the name of the folder neads to appear more prominently, we can imagine it being in place of the adress bar. It would switch between the folder name and the folder adress on a single tap on that space.

**Comment by wmartinmimi** [comment]
Now removed in Little File Explorer v4.14

You can download it via:
- [Github](https://github.com/martinmimigames/little-file-explorer/releases/tag/v4.14)
- [Official website](https://martinmimigames.github.io/projects/little-file-explorer/)
- [F-droid](https://f-droid.org/packages/com.martinmimigames.simplefileexplorer/) (may take a while to update)
