### ISSUE TITLE
[Feature Request] Add `_data` column with absolute file path into the file Intent when opening a file by application

### ISSUE THREAD

**Issue by Wohlstand** [martinmimigames/little-file-explorer#63]
**Describe your idea**
Recently, I found that attempt to open any file via this file manager, never adds an absolute file path into the sent file Intent. Most of file managers that I used, return an absolute file path through the `_data` column, or sent the URI of `file` type with the `path` field being set.

**Describe why you want the idea incorprated**
Some applications do require an absolute file path, because of the necessary to also find resources around. For example, it's a level file for a game engine, and all resources placed at the sub-directory at the same directory as file is placed. When is impossible to recognise the file path, that's means, it's impossible to also open resources, because game engine doesn't know where they are placed.

**[Optional] Describe any implmentations you've considered**
Looks like, this needs a very small tweak at the [FileOpener.java](https://github.com/martinmimigames/little-file-explorer/blob/main/app/src/main/java/com/martinmimigames/simplefileexplorer/FileOpener.java), or extend the [FileProvider.java](https://github.com/martinmimigames/little-file-explorer/blob/main/app/src/main/java/com/martinmimigames/simplefileexplorer/FileProvider.java) to add missing fields, but I don't know yet what to add here...

P.S. Also, seems, the returned Intent lacks fields `_display_name` and `_size`...

**Comment by wmartinmimi** [comment]
Should now be fixed in Little File Explorer v4.14

You can download it via:
- [Github](https://github.com/martinmimigames/little-file-explorer/releases/tag/v4.14)
- [Official website](https://martinmimigames.github.io/projects/little-file-explorer/)
- [F-droid](https://f-droid.org/packages/com.martinmimigames.simplefileexplorer/) (may take a while to update)

**Comment by Wohlstand** [comment]
Works just fine!
Now my gale clearly finds all paths. Thanks!
