### ISSUE TITLE
[Bug] Compilation failed on Android Hedgehog

### ISSUE THREAD

**Issue by lawgimenez** [martinmimigames/little-file-explorer#74]
**Describe the bug**
Currently throwing a compile error

```
Invalid VCS root mapping
The directory <Project>/app/src/main/java/mg/utils is registered as a Git root, but no Git repositories were found there.
```

<img width="355" alt="Screenshot 2023-12-29 at 4 31 00 PM" src="https://github.com/martinmimigames/little-file-explorer/assets/7910468/2abc14c5-b431-4cac-937b-acac420c4abf">

**To Reproduce**
1. Open the project with Android Hedgehog

**Expected Behaviour**
A description of what you expected to happen.

**[Optional] Screenshots**
If applicable, add any screenshots that may help explain your problem.

**[Optional] Versioning  information**
- App Version [e.g. v1.10]
- OS: [e.g. Android 1.0]

**[Optional] Additional information**
Add any other information about the problem that may be useful.

**Comment by wmartinmimi** [comment]
try open the terminal in idea with `Alt-F12`, and run the following command.

```sh
git submodule init
git submodule update
```

Then close Android Hedgehog and open it again.
